# Generated by Django 5.2.5 on 2025-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=25)),
                ('author_language', models.CharField(max_length=20)),
                ('author_age', models.IntegerField()),
                ('author_nationality', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=45)),
                ('book_author', models.CharField(max_length=25)),
                ('book_categorey', models.CharField(max_length=20)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
